Update Backend Jenkins File for Github Push

diff --git a/backend/Jenkinsfile.backend b/backend/Jenkinsfile.backend
--- a/backend/Jenkinsfile.backend
+++ b/backend/Jenkinsfile.backend
@@ -51,15 +51,15 @@ pipeline {
                         echo "Checking repository status: "
                         git status
                     
-                        echo "Adding changes to git: "
+                        echo "--- Checkout main branch or create if missing ---"
+                        git checkout main || git checkout -b main
+                        git pull https://${GIT_USER}:${GIT_TOKEN}@github.com/Kapil-Bhalodiya/E-commerce-Platform.git main || true
+
+                        echo "--- Git Add / Commit / Push ---"
                         git add .
-                        
-                        echo "Commiting changes: "
                         git commit -m "Update backend image to ${IMAGE_TAG}" || echo "No changes to commit"
-                        
-                        echo "Pushing changes to github: {GIT_USER}:${GIT_TOKEN}"
                         git push https://${GIT_USER}:${GIT_TOKEN}@github.com/Kapil-Bhalodiya/E-commerce-Platform.git main
-                    '''
+                        '''
                     }
                 }
             }
